"""Phase 4

Revision ID: 32e59cb40f96
Revises: 50212c3c5ebf
Create Date: 2026-04-19 00:56:22.115003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32e59cb40f96'
down_revision: Union[str, None] = '50212c3c5ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=32), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_number'), 'accounts', ['account_number'], unique=True)
    op.create_table('user_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kem_public_key', sa.LargeBinary(), nullable=False),
    sa.Column('kem_private_key_enc', sa.LargeBinary(), nullable=False),
    sa.Column('kem_salt', sa.LargeBinary(), nullable=False),
    sa.Column('kem_nonce', sa.LargeBinary(), nullable=False),
    sa.Column('rsa_public_key', sa.LargeBinary(), nullable=False),
    sa.Column('rsa_private_key_enc', sa.LargeBinary(), nullable=False),
    sa.Column('rsa_salt', sa.LargeBinary(), nullable=False),
    sa.Column('rsa_nonce', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('transactions', sa.Column('kem_ciphertext', sa.LargeBinary(), nullable=True))
    op.add_column('transactions', sa.Column('aes_ciphertext', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'aes_ciphertext')
    op.drop_column('transactions', 'kem_ciphertext')
    op.drop_table('user_keys')
    op.drop_index(op.f('ix_accounts_account_number'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
