"""Initial schema and Phase 3 Auth

Revision ID: 50212c3c5ebf
Revises: 
Create Date: 2026-04-19 00:42:34.952222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50212c3c5ebf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('anomaly_id', sa.String(length=36), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('anomaly_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=True),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('delta_pct', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('anomaly_id')
    )
    op.create_index('idx_anomaly_detected_at', 'anomalies', ['detected_at'], unique=False)
    op.create_index('idx_anomaly_resolved', 'anomalies', ['resolved'], unique=False)
    op.create_index('idx_anomaly_severity', 'anomalies', ['severity'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_client_id'), 'clients', ['client_id'], unique=True)
    op.create_table('daily_migration_snapshot',
    sa.Column('snapshot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('rsa_count', sa.Integer(), nullable=False),
    sa.Column('mlkem_count', sa.Integer(), nullable=False),
    sa.Column('hybrid_count', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('snapshot_date')
    )
    op.create_index('idx_snapshot_date', 'daily_migration_snapshot', ['snapshot_date'], unique=False)
    op.create_table('key_metadata',
    sa.Column('key_id', sa.String(length=36), nullable=False),
    sa.Column('algorithm', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('rotation_due_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key_id')
    )
    op.create_index('idx_key_algorithm_status', 'key_metadata', ['algorithm', 'status'], unique=False)
    op.create_index('idx_key_created_at', 'key_metadata', ['created_at'], unique=False)
    op.create_index('idx_rotation_due_at', 'key_metadata', ['rotation_due_at'], unique=False)
    op.create_table('key_rotation_audit',
    sa.Column('rotation_id', sa.String(length=36), nullable=False),
    sa.Column('old_key_id', sa.String(length=36), nullable=True),
    sa.Column('new_key_id', sa.String(length=36), nullable=True),
    sa.Column('rotated_at', sa.DateTime(), nullable=False),
    sa.Column('rotation_reason', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('rotation_id')
    )
    op.create_table('security_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('algorithm', sa.String(length=20), nullable=True),
    sa.Column('sender', sa.String(length=128), nullable=True),
    sa.Column('receiver', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_security_algorithm_timestamp', 'security_events', ['algorithm', 'timestamp'], unique=False)
    op.create_index('idx_security_event_type', 'security_events', ['event_type'], unique=False)
    op.create_index('idx_security_timestamp', 'security_events', ['timestamp'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('sender', sa.String(length=128), nullable=False),
    sa.Column('receiver', sa.String(length=128), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('crypto_method', sa.String(length=24), nullable=False),
    sa.Column('key_gen_time_ms', sa.Float(), nullable=False),
    sa.Column('encapsulate_time_ms', sa.Float(), nullable=True),
    sa.Column('encrypt_time_ms', sa.Float(), nullable=False),
    sa.Column('decapsulate_time_ms', sa.Float(), nullable=True),
    sa.Column('decrypt_time_ms', sa.Float(), nullable=False),
    sa.Column('total_time_ms', sa.Float(), nullable=False),
    sa.Column('key_size_bytes', sa.Integer(), nullable=False),
    sa.Column('secret_key_bytes', sa.Integer(), nullable=True),
    sa.Column('ciphertext_size_bytes', sa.Integer(), nullable=False),
    sa.Column('latency_bucket', sa.String(length=32), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('origin_ip', sa.String(length=45), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.LargeBinary(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_event_type'), 'audit_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_jti'), 'sessions', ['jti'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_jti'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_event_type'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('transactions')
    op.drop_index('idx_security_timestamp', table_name='security_events')
    op.drop_index('idx_security_event_type', table_name='security_events')
    op.drop_index('idx_security_algorithm_timestamp', table_name='security_events')
    op.drop_table('security_events')
    op.drop_table('key_rotation_audit')
    op.drop_index('idx_rotation_due_at', table_name='key_metadata')
    op.drop_index('idx_key_created_at', table_name='key_metadata')
    op.drop_index('idx_key_algorithm_status', table_name='key_metadata')
    op.drop_table('key_metadata')
    op.drop_index('idx_snapshot_date', table_name='daily_migration_snapshot')
    op.drop_table('daily_migration_snapshot')
    op.drop_index(op.f('ix_clients_client_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index('idx_anomaly_severity', table_name='anomalies')
    op.drop_index('idx_anomaly_resolved', table_name='anomalies')
    op.drop_index('idx_anomaly_detected_at', table_name='anomalies')
    op.drop_table('anomalies')
    # ### end Alembic commands ###
